### ISSUE TITLE
TypeError when trying to log in

### ISSUE THREAD

**Issue by JarnoRFB** [grindsa/dkb-robo#12] opened 2018-10-30 14:11 UTC
hey nice project! When I try to log in 
```
with DKBRobo(DKB_USER, DKB_PASSWORD) as dkb:
    print(dkb.last_login)
```
I get the following error
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-a1ff75b89985> in <module>
      1 DKB = DKBRobo(dkb_user=DKB_USER, dkb_password=DKB_PASSWORD)
----> 2 DKB.login()
      3 DKB.account_dic

~/.miniconda/envs/banking/lib/python3.7/site-packages/dkb_robo/dkb_robo.py in login(self)
    386 
    387             # parse account date
--> 388             self.account_dic = self.parse_overview(soup)
    389 
    390 

~/.miniconda/envs/banking/lib/python3.7/site-packages/dkb_robo/dkb_robo.py in parse_overview(self, soup)
    578                     overview_dic[counter]['type'] = 'depot'
    579                     link = cols[4 + ontop].find('a', attrs={'class':'evt-depot'})
--> 580                     overview_dic[counter]['transactions'] = self.base_url + link['href']
    581                 except IndexError:
    582                     pass

TypeError: 'NoneType' object is not subscriptable
```
Maybe that's due to the link variable not being filled, but I did not really dig into it.

**Comment by grindsa** [comment] 2018-10-30 19:59
Hi,
thanks for reporting this. I am not 100 percent sure what is causing the issue however I did a quickfix in the devel branch ([9227205](https://github.com/grindsa/dkb-robo/commit/922720516db80be63708127a10f084d8b343c266)) which should hopefully solve the issue. Please give it a try and let me know if it helps.

/Grindsa

**Comment by grindsa** [comment] 2018-12-02 19:32
closed due to missing response. But seems to be fixed :-)

**Comment by wngr** [comment] 2020-03-30 09:22
Might this be a python3 vs python2 related issue? I just ran into the same error using `Python 3.7.6`.

**Comment by grindsa** [comment] 2020-03-30 11:18
hm... is it again a TypeError? Can you please give me the exact error message (including line-numbers)?

**Comment by wngr** [comment] 2020-03-30 11:42
I'm actually not sure I did _The Right Thing (TM)_, when setting up my python environment. For the sake of running the test, I just copied the `dkb_robo` folder into the `doc` folder.
```
➜  doc git:(master) ✗ python3 dkb_example.py  
check your banking app and confirm login...
Traceback (most recent call last):
  File "dkb_example.py", line 27, in <module>
    with DKBRobo(DKB_USER, DKB_PASSWORD) as dkb:
  File "/home/ow/src/dkb-downloads/dkb-robo/doc/dkb_robo/dkb_robo.py", line 60, in __enter__
    self.login()
  File "/home/ow/src/dkb-downloads/dkb-robo/doc/dkb_robo/dkb_robo.py", line 433, in login
    self.account_dic = self.parse_overview(soup_new)
  File "/home/ow/src/dkb-downloads/dkb-robo/doc/dkb_robo/dkb_robo.py", line 722, in parse_overview
    overview_dic[counter]['details'] = self.base_url + link['href']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by grindsa** [comment] 2020-03-30 12:49
Thanks. I pushed a potential fix into the devel branch ([d506283](https://github.com/grindsa/dkb-robo/commit/d50628311cdac5c42a6f0cc8547a536463b7c9d8).  I also updated dkb_example.py as it contains some bugs. Please give it a try and let me know if it works.  It should be enough to copy the dkb_robo folder into the doc folder for testing.

**Comment by wngr** [comment] 2020-03-30 13:20
Thanks for the swift response! I can confirm that the example works with `HEAD` of `devel`.

**Comment by grindsa** [comment] 2020-03-30 14:17
Thx for confirming. Will close the issue.

**Closed** 2020-03-30 14:18 UTC
Labels: bug
