### ISSUE TITLE
scan_documents with path and downloading all from archive fails for most documents

### ISSUE THREAD

**Issue by Luftol** [grindsa/dkb-robo#35] opened 2023-01-17 11:14 UTC
Some douments get fetched, but for most the debug output is:

_download_document()

DKBRobo._get_document(https://www.dkb.de/DkbTransactionBanking/content/mailbox/MessageList.xhtml?$event=getMailboxAttachment&filename=Kontoauszug+Nr.+062_2020+zu+Konto+1234567890&row=136)

https://www.dkb.de:443 "GET /DkbTransactionBanking/content/mailbox/MessageList.xhtml?$event=getMailboxAttachment&filename=Kontoauszug+Nr.+062_2020+zu+Konto+1234567890&row=136 HTTP/1.1" 655 None

Any clue?

Thanks
Florian

**Comment by grindsa** [comment] 2023-01-21 15:39
I can confirm the problem and it looks like a nasty behavior of the DKB webserver. Need to think about a workaround but this may take a couple of days..

Sorry..

**Comment by grindsa** [comment] 2023-01-22 05:43
Fixing was easier than expected. I pushed some changes into the [devel branch](https://github.com/grindsa/dkb-robo/tree/devel) which should address the issue you've reported. Can you re-test?

**Comment by goseind** [comment] 2023-01-23 09:42
Script runs without errors but I only get 125 out of 143 documents in *Wertpapiere* (*Postfach* and *Archiv* combined). I'll try to debug myself later this week.
Thanks a lot for your effort, this tools is a great initative 👍🏼

**Comment by grindsa** [comment] 2023-06-30 16:14
closing as the issue is fixed

**Closed by grindsa** 2023-06-30 16:14 UTC
Labels: bug, fix ready for testing
